spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anno?useSSL=true&useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=UTF%2D8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root@1024.VIP
    driver-class-name: com.mysql.cj.jdbc.Driver